/** Clés TanStack Query centralisées → invalidations cohérentes partout. */
export const qk = {
  me: ['me'] as const,
  cards: (params: object) => ['cards', params] as const,
  card: (id: number) => ['card', id] as const,
  cardInteractions: (id: number) => ['card', id, 'interactions'] as const,
  archetypes: ['archetypes'] as const,
  sets: (params: object) => ['sets', params] as const,
  collection: (params: object) => ['collection', params] as const,
  collectionAll: ['collection'] as const,
  collectionStats: ['collection-stats'] as const,
  products: ['products'] as const,
  product: (id: string) => ['products', id] as const,
  decks: ['decks'] as const,
  deck: (id: string) => ['deck', id] as const,
  wishlist: ['wishlist'] as const,
  metaSuggestions: ['suggestions', 'meta'] as const,
  archetypeSuggestions: ['suggestions', 'archetypes'] as const,
  deckSuggestions: (deckId: string) => ['suggestions', 'deck', deckId] as const,
  generated: (target: object | null, mode: string) =>
    ['suggestions', 'generate', target, mode] as const,
  metaStatus: ['meta-status'] as const,
  playable: ['suggestions', 'playable'] as const,
  officialDecks: (kind: string) => ['suggestions', 'official', kind] as const,
  guide: (fingerprint: string, ai: boolean) => ['guide', fingerprint, ai] as const,
};
