/** Clés TanStack Query centralisées → invalidations cohérentes partout. */
export const qk = {
  me: ['me'] as const,
  cards: (params: object) => ['cards', params] as const,
  card: (id: number) => ['card', id] as const,
  cardInteractions: (id: number) => ['card', id, 'interactions'] as const,
  archetypes: ['archetypes'] as const,
  sets: (params: object) => ['sets', params] as const,
  collection: (params: object) => ['collection', params] as const,
  collectionAll: ['collection'] as const,
  collectionStats: ['collection-stats'] as const,
  products: (params: object = {}) => ['products', params] as const,
  productsAll: ['products'] as const,
  product: (id: string) => ['products', 'detail', id] as const,
  releases: (params: object) => ['releases', params] as const,
  releasesAll: ['releases'] as const,
  releaseSpotlight: ['releases', 'spotlight'] as const,
  releaseFacets: ['releases', 'facets'] as const,
  release: (setId: string) => ['releases', 'detail', setId] as const,
  tags: ['tags'] as const,
  myProfile: ['profile', 'me'] as const,
  profile: (username: string) => ['profile', username] as const,
  friends: ['friends'] as const,
  friendRequests: ['friend-requests'] as const,
  userSearch: (q: string) => ['user-search', q] as const,
  friendsProgress: (setIds: string[]) => ['friends-progress', setIds] as const,
  setFriends: (setId: string) => ['set-friends', setId] as const,
  collectionFacets: ['collection-facets'] as const,
  collectionLanguage: (target: string | undefined) => ['collection-language', target] as const,
  decks: ['decks'] as const,
  deckList: (params: object) => ['decks', params] as const,
  deck: (id: string) => ['deck', id] as const,
  deckStrength: (id: string) => ['deck', id, 'strength'] as const,
  wishlist: ['wishlist'] as const,
  metaSuggestions: ['suggestions', 'meta'] as const,
  archetypeSuggestions: ['suggestions', 'archetypes'] as const,
  deckSuggestions: (deckId: string) => ['suggestions', 'deck', deckId] as const,
  generated: (target: object | null, mode: string) =>
    ['suggestions', 'generate', target, mode] as const,
  metaStatus: ['meta-status'] as const,
  playable: ['suggestions', 'playable'] as const,
  officialDecks: (kind: string) => ['suggestions', 'official', kind] as const,
  duelEngine: ['duel', 'engine'] as const,
  guide: (fingerprint: string, ai: boolean) => ['guide', fingerprint, ai] as const,
};
